# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_1_2/messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17task_1_2/messages.proto\"\x19\n\tnode_init\x12\x0c\n\x04port\x18\x01 \x01(\t\"I\n\x11send_data_request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07num_rep\x18\x02 \x01(\x05\x12\x11\n\tnode_list\x18\x03 \x01(\t\"%\n\x11recv_data_request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_1_2.messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NODE_INIT._serialized_start=27
  _NODE_INIT._serialized_end=52
  _SEND_DATA_REQUEST._serialized_start=54
  _SEND_DATA_REQUEST._serialized_end=127
  _RECV_DATA_REQUEST._serialized_start=129
  _RECV_DATA_REQUEST._serialized_end=166
# @@protoc_insertion_point(module_scope)
