# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\";\n\x11storedata_request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0cmax_erasures\x18\x02 \x01(\x05\"#\n\x0fgetdata_request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"l\n\x16getdataErasure_request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0cmax_erasures\x18\x02 \x01(\x05\x12\x11\n\tfile_size\x18\x03 \x01(\x05\x12\x17\n\x0f\x63oded_fragments\x18\x04 \x01(\t\"-\n\x06header\x12#\n\x0crequest_type\x18\x01 \x01(\x0e\x32\r.request_type*K\n\x0crequest_type\x12\x12\n\x0eMESSAGE_ENCODE\x10\x00\x12\x12\n\x0eMESSAGE_DECODE\x10\x01\x12\x13\n\x0fMESSAGE_RESPONS\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST_TYPE._serialized_start=273
  _REQUEST_TYPE._serialized_end=348
  _STOREDATA_REQUEST._serialized_start=18
  _STOREDATA_REQUEST._serialized_end=77
  _GETDATA_REQUEST._serialized_start=79
  _GETDATA_REQUEST._serialized_end=114
  _GETDATAERASURE_REQUEST._serialized_start=116
  _GETDATAERASURE_REQUEST._serialized_end=224
  _HEADER._serialized_start=226
  _HEADER._serialized_end=271
# @@protoc_insertion_point(module_scope)
